[package]
name = "clippy"
version = "0.0.88"
authors = [
	"Manish Goregaokar <manishsmail@gmail.com>",
	"Andre Bogus <bogusandre@gmail.com>",
	"Georg Brandl <georg@python.org>",
	"Martin Carton <cartonmartin@gmail.com>",
	"Oliver Schneider <clippy-iethah7aipeen8neex1a@oli-obk.de>"
]
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
repository = "https://github.com/Manishearth/rust-clippy"
readme = "README.md"
license = "MPL-2.0"
keywords = ["clippy", "lint", "plugin"]

[lib]
name = "clippy"
plugin = true
test = false

[[bin]]
name = "cargo-clippy"
test = false

[dependencies]
# begin automatic update
clippy_lints = { version = "0.0.88", path = "clippy_lints" }
# end automatic update

[dev-dependencies]
compiletest_rs = "0.2.1"
lazy_static = "0.1.15"
regex = "0.1.71"
rustc-serialize = "0.3"
clippy-mini-macro-test = { version = "0.1", path = "mini-macro" }
serde = "0.7"


[features]
debugging = []
